input_field: text
filters:
  - name: nemo_curator.filters.heuristic_filter.NonAlphaNumericFilter
    params:
      max_non_alpha_numeric_to_text_ratio: 0.25
  - name: nemo_curator.filters.heuristic_filter.SymbolsToWordsFilter
    params:
      max_symbol_to_word_ratio: 0.1
  - name: nemo_curator.filters.heuristic_filter.NumbersFilter
    params:
      max_number_to_text_ratio: 0.15
  - name: nemo_curator.filters.heuristic_filter.UrlsFilter
    params:
      max_url_to_text_ratio: 0.2
  - name: nemo_curator.filters.heuristic_filter.WhiteSpaceFilter
    params:
      max_white_space_ratio: 0.25
  - name: nemo_curator.filters.heuristic_filter.ParenthesesFilter
    params:
      max_parentheses_ratio: 0.1
  - name: nemo_curator.filters.heuristic_filter.RepeatedLinesFilter
    params:
      max_repeated_line_fraction: 0.7
  - name: nemo_curator.filters.heuristic_filter.RepeatedParagraphsFilter
    params:
      max_repeated_paragraphs_ratio: 0.7
  - name: nemo_curator.filters.heuristic_filter.WordCountFilter
    params:
      min_words: 50
      max_words: 100000
  - name: nemo_curator.filters.heuristic_filter.BoilerPlateStringFilter
    params:
      remove_if_at_top_or_bottom: True
      max_boilerplate_string_ratio: 0.4
  - name: nemo_curator.filters.heuristic_filter.LongWordFilter
    params:
      max_word_length: 1000
  - name: nemo_curator.filters.heuristic_filter.PunctuationFilter
    params:
      max_num_sentences_without_endmark_ratio: 0.85
  - name: nemo_curator.filters.heuristic_filter.EllipsisFilter
    params:
      max_num_lines_ending_with_ellipsis_ratio: 0.3